name = "hazardcleanupcanada"
main = "dist/_worker.js/index.js"
compatibility_date = "2024-12-24"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "hazardcleanup.ca", custom_domain = true }
]

[assets]
directory = "./dist"
binding = "ASSETS"

[vars]
EMAIL_FROM = "website@hazardcleanup.ca"
EMAIL_TO = "help@hazardcleanup.ca"
POSTMARK_MESSAGE_STREAM = "outbound"