name = "hazardcleanupcanada"
pages_build_output_dir = "dist"
compatibility_date = "2024-12-24"

[vars]
EMAIL_FROM = "website@hazardcleanup.ca"
EMAIL_TO = "help@hazardcleanup.ca"
POSTMARK_MESSAGE_STREAM = "outbound"